const fakeData = [
  {
    name: "Pipo",
    specie: "Perro",
    photos: [
      "https://www.olavarria.gov.ar/antirrabica-para-perros-callejeros/",
    ],
    gender: "Macho",
    age: "2 años",
    size: "grande",
    location: "Villa Crespo, Buenos Aires",
    personality: "Tranquilo",
    vaccinated: true,
    foundation: "Colitas al rescate",
  },
  {
    name: "Lula",
    photos: [
      "https://cdni.russiatoday.com/actualidad/public_images/2022.04/article/626ad2b7e9ff71073e4ab35a.jpeg",
    ],
    specie: "Perro",
    gender: "Hembra",
    age: "1 año",
    size: "mediano",
    location: "La Plata, Buenos Aires",
    personality: "Enérgica",
    vaccinated: true,
    foundation: "Colitas al rescate",
  },
  {
    name: "Moni",
    photos: [
      "https://www.publico.es/files/module_big_mobile//files/crop//uploads/2022/08/07/62efd8bc88e29.r_1659938929253.0-0-480-270.jpeg",
    ],
    specie: "Gato",
    gender: "Hembra",
    age: "6 meses",
    size: "mediano",
    location: "Lanús, Buenos Aires",
    personality: "Dormilona",
    vaccinated: true,
    foundation: "Rescata2",
  },
  {
    name: "Turron",
    photos: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/220px-Cat_November_2010-1a.jpg",
    ],
    specie: "Gato",
    gender: "Macho",
    age: "9 meses",
    size: "mediano",
    location: "Caballito, Buenos Aires",
    personality: "Activo",
    vaccinated: true,
    foundation: "Rescata2",
  },
];
